a={"ram","shyam","hari","gita","sita","sita"}
b={"ram","shyam","hari","gita","sita","sita"}
c={"karan","raju","sita","gita","sita"}

#add
a.add("sita")

#remove
a.remove("sita")

#discard
a.discard("sita")

#pop
a.pop()

#clear
a.clear()

#copy
b.copy()

#union
d=a.union(b)

#intersection
e=a.intersection(b)

#difference

f=a.difference(b)


#symmetric_difference
g=a.symmetric_difference(b)

#issubset
h=a.issubset(b)

#issuperset

i=a.issuperset(b)