import numpy as np
backed_food=[200,120,400,130,150,500,450,300,250,350]
a=np.array(backed_food)
print(np.mean(backed_food))
print(np.mod(backed_food))
print(np.std(backed_food))
print(np.var(backed_food))      
print(np.median(backed_food))
print(np.min(backed_food))
print(np.max(backed_food))
print(np.sum(backed_food))
print(np.prod(backed_food))
print(np.sort(backed_food))
print(np.argsort(backed_food))